version: '3'
services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: sit722_part5_gcgd_user
      POSTGRES_PASSWORD: QUgm113XPDhaZXPJyuKK3cdjMsyQFEnA
      POSTGRES_DB: sit722_part5_gcgd 
    ports:
      - "5432:5432"
    restart: "on-failure"

  book-catalog: 
    platform: linux/amd64
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_part5_gcgd_user:QUgm113XPDhaZXPJyuKK3cdjMsyQFEnA@dpg-crtnu1l2ng1s73c9hepg-a.singapore-postgres.render.com/sit722_part5_gcgd
    restart: "on-failure"

  inventory-management: 
    platform: linux/amd64  
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://sit722_part5_gcgd_user:QUgm113XPDhaZXPJyuKK3cdjMsyQFEnA@dpg-crtnu1l2ng1s73c9hepg-a.singapore-postgres.render.com/sit722_part5_gcgd
    depends_on:
      - db
    restart: "on-failure"