apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory-management:$VERSION
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: "postgresql://m224246429_user:kFXWFcBhlWt8poRTVgJJMnitxoSgXaIc@dpg-crna0c68ii6s73en725g-a.singapore-postgres.render.com/m224246429"

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer