name: Terraform Infrastructure Deployment

# Trigger the workflow on push or pull requests to the main branch
on:

 # Allows deployment to be invoked manually through the GitHub Actions user interface.
  
  workflow_dispatch: 

# Define the jobs that will run within this workflow
jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    # Define environment variables (replace placeholders with your actual values)
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}        # Azure Client ID (for Azure)
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} # Azure Client Secret
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} # Azure Subscription ID
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}        
      NAME: terraform
      DIRECTORY: terraform

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0  # Specify the Terraform version you want

      # Step 3: Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Terraform Apply (only runs on push, not pull requests)
      - name: Terraform Apply
        run: terraform apply -auto-approve
