name: Terraform Infrastructure Deployment

# Trigger the workflow on push or pull requests to the main branch
on:

 # Allows deployment to be invoked manually through the GitHub Actions user interface.
  
  workflow_dispatch: 

# Define the jobs that will run within this workflow
jobs:                                    
  hello-world:                           
    runs-on: ubuntu-latest               
 
    steps:                               
      - uses: actions/checkout@v3        
 
      - name: Run the shell script       
        run: ./index.sh   